=== ogcincubator/bblocks-seadots/build/annotated/hosted/seadots/catalog-input/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "SeaDOTs Catalog Input",
  "description": "STAC Item profile for a concrete input consumed by a SeaDOTs execution.\n",
  "type": "object",
  "required": [
    "id",
    "type",
    "stac_version",
    "properties",
    "geometry",
    "bbox",
    "assets"
  ],
  "properties": {
    "id": {
      "type": "string",
      "x-jsonld-id": "@id"
    },
    "type": {
      "const": "Feature",
      "x-jsonld-id": "@type"
    },
    "stac_version": {
      "type": "string",
      "x-jsonld-id": "https://stacspec.org/vocab#stac_version"
    },
    "collection": {
      "type": "string",
      "x-jsonld-id": "http://purl.org/dc/terms/isPartOf",
      "x-jsonld-type": "@id"
    },
    "geometry": {
      "type": [
        "object",
        "null"
      ],
      "x-jsonld-id": "https://purl.org/geojson/vocab#geometry"
    },
    "bbox": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "x-jsonld-id": "https://purl.org/geojson/vocab#bbox"
    },
    "properties": {
      "type": "object",
      "required": [
        "title",
        "description",
        "datetime"
      ],
      "properties": {
        "title": {
          "type": "string",
          "x-jsonld-id": "http://purl.org/dc/terms/title"
        },
        "description": {
          "type": "string",
          "x-jsonld-id": "http://purl.org/dc/terms/description"
        },
        "datetime": {
          "type": "string",
          "format": "date-time",
          "x-jsonld-id": "http://purl.org/dc/terms/date",
          "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
        },
        "role": {
          "type": "string",
          "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#role"
        },
        "convention": {
          "type": "string",
          "description": "Optional metadata convention declaration, e.g. CF-1.10.",
          "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#metadataConvention"
        },
        "cf:parameter": {
          "type": "array",
          "description": "Optional STAC CF extension parameter declarations.",
          "items": {
            "type": "object",
            "required": [
              "name"
            ],
            "properties": {
              "name": {
                "type": "string",
                "description": "CF standard name or local parameter name.",
                "x-jsonld-id": "http://purl.org/dc/terms/title"
              },
              "schema": {
                "type": "string",
                "format": "uri",
                "description": "Vocabulary or schema URI for the parameter name.",
                "x-jsonld-id": "https://schema.org/"
              },
              "unit": {
                "type": "string",
                "description": "Unit string or URI for the parameter.",
                "x-jsonld-id": "http://purl.org/dc/terms/format"
              },
              "description": {
                "type": "string",
                "x-jsonld-id": "http://purl.org/dc/terms/description"
              }
            }
          },
          "x-jsonld-id": "https://stac-extensions.github.io/cf/v0.2.0/schema.json#parameter",
          "x-jsonld-container": "@set"
        }
      },
      "additionalProperties": true,
      "x-jsonld-id": "https://purl.org/geojson/vocab#properties"
    },
    "assets": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [
          "href"
        ],
        "properties": {
          "href": {
            "type": "string",
            "x-jsonld-id": "@id"
          },
          "type": {
            "type": "string",
            "x-jsonld-id": "@type"
          },
          "title": {
            "type": "string",
            "x-jsonld-id": "http://purl.org/dc/terms/title"
          },
          "roles": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "x-jsonld-id": "https://stacspec.org/vocab#assets"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "rel",
          "href"
        ],
        "properties": {
          "rel": {
            "type": "string",
            "x-jsonld-id": "http://www.w3.org/ns/iana/link-relations/relation"
          },
          "href": {
            "type": "string",
            "x-jsonld-id": "@id"
          },
          "type": {
            "type": "string",
            "x-jsonld-id": "@type"
          },
          "title": {
            "type": "string",
            "x-jsonld-id": "http://purl.org/dc/terms/title"
          }
        }
      },
      "x-jsonld-id": "http://www.w3.org/ns/iana/link-relations/relation",
      "x-jsonld-container": "@set"
    }
  },
  "x-jsonld-extra-terms": {
    "Feature": "https://purl.org/geojson/vocab#Feature",
    "coordinates": "https://purl.org/geojson/vocab#coordinates",
    "itemType": "http://purl.org/dc/terms/type",
    "conformsTo": {
      "x-jsonld-id": "http://purl.org/dc/terms/conformsTo",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "keywords": {
      "x-jsonld-id": "http://www.w3.org/ns/dcat#keyword",
      "x-jsonld-container": "@set"
    },
    "themes": {
      "x-jsonld-id": "http://www.w3.org/ns/dcat#theme",
      "x-jsonld-container": "@set"
    },
    "license": {
      "x-jsonld-id": "http://purl.org/dc/terms/license",
      "x-jsonld-type": "@id"
    },
    "created": {
      "x-jsonld-id": "http://purl.org/dc/terms/created",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "updated": {
      "x-jsonld-id": "http://purl.org/dc/terms/modified",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "applicationCategory": "https://schema.org/applicationCategory",
    "softwareVersion": "https://schema.org/softwareVersion",
    "programmingLanguage": "https://schema.org/programmingLanguage",
    "applicationPackage": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#applicationPackage",
      "x-jsonld-type": "@id"
    },
    "workflow": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#hadPlan",
      "x-jsonld-type": "@id"
    },
    "inputs": {
      "x-jsonld-id": "https://w3id.org/apkg/terms/inputs",
      "x-jsonld-container": "@set"
    },
    "outputs": {
      "x-jsonld-id": "https://w3id.org/apkg/terms/outputs",
      "x-jsonld-container": "@set"
    },
    "profileId": {
      "x-jsonld-id": "http://purl.org/dc/terms/conformsTo",
      "x-jsonld-type": "@id"
    },
    "required": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#requiredInput",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#boolean"
    },
    "class": "https://w3id.org/cwl/cwl#class",
    "requirements": {
      "x-jsonld-id": "https://w3id.org/cwl/cwl#requirements",
      "x-jsonld-container": "@set"
    },
    "version": "http://purl.org/dc/terms/hasVersion",
    "method": "http://purl.org/dc/terms/method",
    "startTime": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#startedAtTime",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "endTime": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#endedAtTime",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "status": "https://w3id.org/ogc/hosted/seadots/catalog#status",
    "parameters": "https://w3id.org/ogc/hosted/seadots/catalog#parameters",
    "timeBoundaryStart": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#timeBoundaryStart",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#date"
    },
    "timeBoundaryEnd": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#timeBoundaryEnd",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#date"
    },
    "application": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#used",
      "x-jsonld-type": "@id"
    },
    "activity": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#activity",
      "x-jsonld-type": "@id"
    },
    "inputRecords": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#used",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "outputRecords": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#generated",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "agent": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#wasAssociatedWith",
      "x-jsonld-type": "@id"
    },
    "configuration": "https://w3id.org/ogc/hosted/seadots/catalog#configuration",
    "containerImage": "https://w3id.org/ogc/hosted/seadots/catalog#containerImage",
    "data": "https://stacspec.org/vocab#data",
    "derivedFrom": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#wasDerivedFrom",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "mediaType": "http://purl.org/dc/terms/format",
    "dockerPull": "https://w3id.org/ogc/hosted/seadots/catalog#dockerPull"
  },
  "x-jsonld-vocab": "https://w3id.org/ogc/hosted/seadots/catalog#",
  "x-jsonld-prefixes": {
    "geojson": "https://purl.org/geojson/vocab#",
    "dcterms": "http://purl.org/dc/terms/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "schema": "https://schema.org/",
    "seadots": "https://w3id.org/ogc/hosted/seadots/catalog#",
    "prov": "http://www.w3.org/ns/prov#",
    "apkg": "https://w3id.org/apkg/terms/",
    "cwl": "https://w3id.org/cwl/cwl#",
    "stac": "https://stacspec.org/vocab#",
    "cf": "https://stac-extensions.github.io/cf/v0.2.0/schema.json#"
  }
}

=== ogcincubator/bblocks-seadots/build/tests/hosted/seadots/catalog-input/example_1_1.json
{
  "id": "aoi-utsira",
  "type": "Feature",
  "stac_version": "1.0.0",
  "collection": "seadots-inputs",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          4.7,
          59.1
        ],
        [
          5.0,
          59.1
        ],
        [
          5.0,
          59.4
        ],
        [
          4.7,
          59.4
        ],
        [
          4.7,
          59.1
        ]
      ]
    ]
  },
  "bbox": [
    4.7,
    59.1,
    5.0,
    59.4
  ],
  "properties": {
    "title": "Utsira area of interest",
    "description": "Example area-of-interest input for a SeaDOTs execution.",
    "datetime": "2026-05-26T00:00:00Z",
    "role": "input",
    "convention": "CF-1.10",
    "cf:parameter": [
      {
        "name": "area",
        "schema": "http://vocab.nerc.ac.uk/standard_name/",
        "unit": "m2",
        "description": "Optional CF-style parameter declaration for spatial input extent."
      }
    ]
  },
  "assets": {
    "data": {
      "href": "https://example.org/seadots/inputs/aoi-utsira.geojson",
      "type": "application/geo+json",
      "title": "AOI GeoJSON"
    }
  },
  "links": [
    {
      "rel": "describedby",
      "href": "bblocks://ogc.hosted.seadots.catalog-input",
      "type": "application/schema+json"
    }
  ]
}

=== ogcincubator/bblocks-seadots/build/tests/hosted/seadots/catalog-output/example_1_1.json
{
  "id": "reef-biomass-result",
  "type": "Feature",
  "stac_version": "1.0.0",
  "collection": "seadots-outputs",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          4.7,
          59.1
        ],
        [
          5.0,
          59.1
        ],
        [
          5.0,
          59.4
        ],
        [
          4.7,
          59.4
        ],
        [
          4.7,
          59.1
        ]
      ]
    ]
  },
  "bbox": [
    4.7,
    59.1,
    5.0,
    59.4
  ],
  "properties": {
    "title": "Reef biomass result",
    "description": "Example output product generated by a SeaDOTs execution.",
    "datetime": "2026-05-26T09:03:00Z",
    "role": "output",
    "convention": "CF-1.10",
    "cf:parameter": [
      {
        "name": "biomass",
        "schema": "http://vocab.nerc.ac.uk/standard_name/",
        "unit": "kg",
        "description": "Optional CF-style parameter declaration for the output quantity."
      }
    ],
    "derivedFrom": [
      "https://w3id.org/ogc/hosted/seadots/catalog/input/aoi-utsira"
    ]
  },
  "assets": {
    "data": {
      "href": "https://example.org/seadots/outputs/reef-biomass-result.json",
      "type": "application/json",
      "title": "Reef biomass JSON result"
    }
  },
  "links": [
    {
      "rel": "describedby",
      "href": "bblocks://ogc.hosted.seadots.catalog-output",
      "type": "application/schema+json"
    },
    {
      "rel": "derived_from",
      "href": "https://w3id.org/ogc/hosted/seadots/catalog/input/aoi-utsira"
    },
    {
      "rel": "via",
      "href": "https://w3id.org/ogc/hosted/seadots/catalog/execution/reef-effect-run-001"
    }
  ]
}
