=== ogcincubator/bblocks-seadots/build/annotated/hosted/seadots/catalog-application/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "SeaDOTs Catalog Application",
  "description": "OGC API Records profile for a reusable application, workflow, model, transformer, or process.\n",
  "allOf": [
    {
      "$ref": "https://ogcincubator.github.io/geodcat-ogcapi-records/build/annotated/geo/geodcat/geodcat-records/schema.json"
    }
  ],
  "type": "object",
  "required": [
    "id",
    "type",
    "itemType",
    "properties"
  ],
  "properties": {
    "id": {
      "type": "string",
      "x-jsonld-id": "@id"
    },
    "type": {
      "const": "Feature",
      "x-jsonld-id": "@type"
    },
    "itemType": {
      "const": "record",
      "x-jsonld-id": "http://purl.org/dc/terms/type"
    },
    "conformsTo": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "x-jsonld-id": "http://purl.org/dc/terms/conformsTo",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "geometry": {
      "type": [
        "object",
        "null"
      ],
      "x-jsonld-id": "https://purl.org/geojson/vocab#geometry"
    },
    "bbox": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "x-jsonld-id": "https://purl.org/geojson/vocab#bbox"
    },
    "properties": {
      "type": "object",
      "required": [
        "title",
        "description",
        "type",
        "applicationCategory"
      ],
      "properties": {
        "title": {
          "type": "string",
          "x-jsonld-id": "http://purl.org/dc/terms/title"
        },
        "description": {
          "type": "string",
          "x-jsonld-id": "http://purl.org/dc/terms/description"
        },
        "type": {
          "const": "Application",
          "x-jsonld-id": "@type"
        },
        "applicationCategory": {
          "type": "string",
          "enum": [
            "DigitalTwinApplication",
            "Workflow",
            "Transform",
            "Model",
            "Service"
          ],
          "x-jsonld-id": "https://schema.org/applicationCategory"
        },
        "softwareVersion": {
          "type": "string",
          "x-jsonld-id": "https://schema.org/softwareVersion"
        },
        "programmingLanguage": {
          "type": "string",
          "x-jsonld-id": "https://schema.org/programmingLanguage"
        },
        "applicationPackage": {
          "type": "string",
          "format": "uri",
          "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#applicationPackage",
          "x-jsonld-type": "@id"
        },
        "workflow": {
          "type": "string",
          "format": "uri",
          "x-jsonld-id": "http://www.w3.org/ns/prov#hadPlan",
          "x-jsonld-type": "@id"
        },
        "inputs": {
          "type": "array",
          "description": "Input profiles accepted by this application.",
          "items": {
            "type": "object",
            "required": [
              "profileId",
              "required"
            ],
            "properties": {
              "profileId": {
                "type": "string",
                "description": "URI or fully qualified building block identifier of the accepted input profile.",
                "x-jsonld-id": "http://purl.org/dc/terms/conformsTo",
                "x-jsonld-type": "@id"
              },
              "required": {
                "type": "boolean",
                "description": "Whether this input profile is required to execute the application.",
                "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#requiredInput",
                "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#boolean"
              },
              "role": {
                "type": "string",
                "description": "Application-specific input role.",
                "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#role"
              },
              "description": {
                "type": "string",
                "x-jsonld-id": "http://purl.org/dc/terms/description"
              }
            }
          },
          "x-jsonld-id": "https://w3id.org/apkg/terms/inputs",
          "x-jsonld-container": "@set"
        },
        "outputs": {
          "type": "array",
          "description": "Output profiles produced by this application.",
          "items": {
            "type": "object",
            "required": [
              "profileId",
              "required"
            ],
            "properties": {
              "profileId": {
                "type": "string",
                "description": "URI or fully qualified building block identifier of the produced output profile.",
                "x-jsonld-id": "http://purl.org/dc/terms/conformsTo",
                "x-jsonld-type": "@id"
              },
              "required": {
                "type": "boolean",
                "description": "Whether this output profile is always produced by the application.",
                "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#requiredInput",
                "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#boolean"
              },
              "role": {
                "type": "string",
                "description": "Application-specific output role.",
                "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#role"
              },
              "description": {
                "type": "string",
                "x-jsonld-id": "http://purl.org/dc/terms/description"
              }
            }
          },
          "x-jsonld-id": "https://w3id.org/apkg/terms/outputs",
          "x-jsonld-container": "@set"
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-jsonld-id": "http://www.w3.org/ns/dcat#keyword",
          "x-jsonld-container": "@set"
        },
        "license": {
          "type": "string",
          "format": "uri",
          "x-jsonld-id": "http://purl.org/dc/terms/license",
          "x-jsonld-type": "@id"
        }
      },
      "additionalProperties": true,
      "x-jsonld-id": "https://purl.org/geojson/vocab#properties"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "rel",
          "href"
        ],
        "properties": {
          "rel": {
            "type": "string",
            "x-jsonld-id": "http://www.w3.org/ns/iana/link-relations/relation"
          },
          "href": {
            "type": "string",
            "x-jsonld-id": "@id"
          },
          "type": {
            "type": "string",
            "x-jsonld-id": "@type"
          },
          "title": {
            "type": "string",
            "x-jsonld-id": "http://purl.org/dc/terms/title"
          }
        }
      },
      "x-jsonld-id": "http://www.w3.org/ns/iana/link-relations/relation",
      "x-jsonld-container": "@set"
    }
  },
  "x-jsonld-extra-terms": {
    "Feature": "https://purl.org/geojson/vocab#Feature",
    "coordinates": "https://purl.org/geojson/vocab#coordinates",
    "name": "http://purl.org/dc/terms/title",
    "themes": {
      "x-jsonld-id": "http://www.w3.org/ns/dcat#theme",
      "x-jsonld-container": "@set"
    },
    "created": {
      "x-jsonld-id": "http://purl.org/dc/terms/created",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "updated": {
      "x-jsonld-id": "http://purl.org/dc/terms/modified",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "class": "https://w3id.org/cwl/cwl#class",
    "requirements": {
      "x-jsonld-id": "https://w3id.org/cwl/cwl#requirements",
      "x-jsonld-container": "@set"
    },
    "version": "http://purl.org/dc/terms/hasVersion",
    "method": "http://purl.org/dc/terms/method",
    "startTime": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#startedAtTime",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "endTime": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#endedAtTime",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "status": "https://w3id.org/ogc/hosted/seadots/catalog#status",
    "parameters": "https://w3id.org/ogc/hosted/seadots/catalog#parameters",
    "timeBoundaryStart": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#timeBoundaryStart",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#date"
    },
    "timeBoundaryEnd": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#timeBoundaryEnd",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#date"
    },
    "application": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#used",
      "x-jsonld-type": "@id"
    },
    "activity": {
      "x-jsonld-id": "https://w3id.org/ogc/hosted/seadots/catalog#activity",
      "x-jsonld-type": "@id"
    },
    "inputRecords": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#used",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "outputRecords": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#generated",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "agent": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#wasAssociatedWith",
      "x-jsonld-type": "@id"
    },
    "configuration": "https://w3id.org/ogc/hosted/seadots/catalog#configuration",
    "containerImage": "https://w3id.org/ogc/hosted/seadots/catalog#containerImage",
    "stac_version": "https://stacspec.org/vocab#stac_version",
    "collection": {
      "x-jsonld-id": "http://purl.org/dc/terms/isPartOf",
      "x-jsonld-type": "@id"
    },
    "datetime": {
      "x-jsonld-id": "http://purl.org/dc/terms/date",
      "x-jsonld-type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "convention": "https://w3id.org/ogc/hosted/seadots/catalog#metadataConvention",
    "cf:parameter": {
      "x-jsonld-id": "https://stac-extensions.github.io/cf/v0.2.0/schema.json#parameter",
      "x-jsonld-container": "@set"
    },
    "unit": "http://purl.org/dc/terms/format",
    "assets": "https://stacspec.org/vocab#assets",
    "data": "https://stacspec.org/vocab#data",
    "derivedFrom": {
      "x-jsonld-id": "http://www.w3.org/ns/prov#wasDerivedFrom",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "mediaType": "http://purl.org/dc/terms/format",
    "dockerPull": "https://w3id.org/ogc/hosted/seadots/catalog#dockerPull"
  },
  "x-jsonld-vocab": "https://w3id.org/ogc/hosted/seadots/catalog#",
  "x-jsonld-prefixes": {
    "geojson": "https://purl.org/geojson/vocab#",
    "dcterms": "http://purl.org/dc/terms/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "schema": "https://schema.org/",
    "seadots": "https://w3id.org/ogc/hosted/seadots/catalog#",
    "prov": "http://www.w3.org/ns/prov#",
    "apkg": "https://w3id.org/apkg/terms/",
    "cwl": "https://w3id.org/cwl/cwl#",
    "stac": "https://stacspec.org/vocab#",
    "cf": "https://stac-extensions.github.io/cf/v0.2.0/schema.json#"
  }
}

=== ogcincubator/bblocks-seadots/_sources/catalog-application/examples/application-record.json
{
  "id": "https://w3id.org/ogc/hosted/seadots/catalog/application/reef-effect",
  "type": "Feature",
  "itemType": "record",
  "conformsTo": [
    "https://docs.ogc.org/is/20-004/20-004.html"
  ],
  "geometry": null,
  "bbox": [

  ],
  "properties": {
    "title": "Utsira reef-effect biomass application",
    "description": "Reusable application record for estimating reef-associated biomass around floating wind infrastructure.",
    "type": "Application",
    "applicationCategory": "DigitalTwinApplication",
    "softwareVersion": "0.1.0",
    "programmingLanguage": "Python",
    "applicationPackage": "https://w3id.org/ogc/hosted/seadots/catalog/application-package/reef-effect",
    "workflow": "https://w3id.org/ogc/hosted/seadots/catalog/workflow/reef-effect",
    "inputs": [
      {
        "profileId": "ogc.hosted.seadots.catalog-input",
        "required": true,
        "role": "catalog-input",
        "description": "Generic STAC input item accepted by this application."
      },
      {
        "profileId": "ogc.hosted.seadots.area-of-interest",
        "required": true,
        "role": "area-of-interest",
        "description": "GeoJSON Feature defining the spatial area for the calculation."
      },
      {
        "profileId": "ogc.hosted.seadots.benthic-biomass-density-mareano",
        "required": false,
        "role": "benthic-biomass-density",
        "description": "Optional baseline benthic biomass-density input profile."
      }
    ],
    "outputs": [
      {
        "profileId": "ogc.hosted.seadots.catalog-output",
        "required": true,
        "role": "catalog-output",
        "description": "Generic STAC output item produced by this application."
      },
      {
        "profileId": "ogc.hosted.seadots.reef-effect-output",
        "required": true,
        "role": "reef-biomass-result",
        "description": "Structured reef-effect biomass output record."
      }
    ],
    "keywords": [
      "open-science",
      "digital-twin",
      "offshore-wind"
    ],
    "license": "https://creativecommons.org/licenses/by/4.0/"
  },
  "links": [
    {
      "rel": "describedby",
      "href": "bblocks://ogc.hosted.seadots.catalog-application",
      "type": "application/schema+json"
    },
    {
      "rel": "application-package",
      "href": "https://w3id.org/ogc/hosted/seadots/catalog/application-package/reef-effect",
      "type": "application/json"
    },
    {
      "rel": "workflow",
      "href": "https://w3id.org/ogc/hosted/seadots/catalog/workflow/reef-effect",
      "type": "application/json"
    }
  ]
}
